### PR TITLE
Balanced weapons and added new sounds

### PR DESCRIPTION
**Pull request by StaticXNation**
Balanced all KOTOR weapons and added new sounds for each. Balanced Naboo Security Pistol, Papanoid, Rebel Pilot Pistol, AuraSing Pistol, B2 Blaster Pistol, Black Sun Pistol, Mercenary Pistol, Deathwatch Weapons, Steela Pistol, and DC-17 Chrome.

### CODE REVIEW

**Comment by Servius** [comment]
@StaticXNation Please take a different approach to making the tiered kotor weapons unique. The gameplay between each should genuinely be different.

**Comment by StaticXNation** [comment]
I did make them different. With the pistols, I made each damage and recoil unique to each tier. So T1 is the worst for damage and recoil and T4 is the best. For the rifles, I made the RPM and recoil unique to each tier. So T1 is the worst for RPM and recoil and T5 is the best. This is what you asked me to do so I did it. 

Could you specify what approach you'd want me to make?

**Comment by Servius** [comment]
As in, please follow the standard for damage. Ie all weapons do 50 damage unless its an ehanced/inherently strong weapon like a gauss rifle or the dlt-19. Take a look at spread, kick, iron accuracy, zoom (found down in the 3dscoped base section of the scoped sweps), etc.

**Comment by StaticXNation** [comment]
I didn't think damage mattered since before, the damage was literally random with the new weapons. With my changes, they progress through each tier rather than being random.

**Comment by StaticXNation** [comment]
I think you should get someone else to change spread, iron accuracy, and zoom. I don't think I'm qualified on what's a good value for either of those. I just edited what I thought needed changing. I can change the damage on the tiered pistols, but I think the tiered rifles are fine and is as much as I can do.

**Pull request merged**
